### PR TITLE
WASM support

### LINKED ISSUE #5: Support stackblitz
Right now this breaks all bundlers on Stackblitz:

```
Error: Cannot load native addon because loading addons is disabled: /home/projects/stackblitz-starters-8yuaei/node_modules/unplugin-parcel-macros-linux-x64-musl/unplugin-parcel-macros.linux-x64-musl.node
    at process.dlopen (https://stackblitzstarters8yuaei-h1h4.w-credentialless-staticblitz.com/blitz.d0228c83.js:352:50455)
```

### PR DESCRIPTION
**Pull request by devongovett**
Closes #5

### CODE REVIEW

File: wasm.mjs [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+  // The code here is also partially based on https://github.com/GoogleChromeLabs/asyncify
+
+  let {exports} = env;
+  let {asyncify_get_state, asyncify_start_unwind, asyncify_stop_unwind, asyncify_start_rewind, asyncify_stop_rewind} = instance.exports;
+
+  // allocate __asyncify_data
+  // Stack data goes right after the initial descriptor.
+  let DATA_ADDR = instance.exports.napi_wasm_malloc(8 + 4096);
+  let DATA_START = DATA_ADDR + 8;
+  let DATA_END = DATA_ADDR + 8 + 4096;
```
Comment (reidbarber) [inline wasm.mjs]: Bumping this buffer size up fixes our style macro issue in StackBlitz:

Before: https://stackblitz.com/edit/4tntshsg?file=src%2FExample.tsx

After: https://stackblitz.com/edit/cqmykkxj?file=patch-macros.mjs
